import "@/app/globals.css";
import NavbarComponent from "@/components/layout/NavbarComponent";
import React from "react";

import {config} from '@fortawesome/fontawesome-svg-core' // 👈
import '@fortawesome/fontawesome-svg-core/styles.css'
import MinimalFooterComponent from "@/components/layout/MinimalFooterComponent"; // 👈
config.autoAddCss = false //

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" data-theme="forest">
        <body
            // className=" pt-[76px]"
        >
        <NavbarComponent/>
        <div>
            {children}
        </div>
        <MinimalFooterComponent></MinimalFooterComponent></body>
        </html>
    );
}
