import "@/app/globals.css";
import NavbarComponent from "@/components/layout/NavbarComponent";
import React from "react";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" data-theme="emerald">
        <body>
        <NavbarComponent/>
        {children}</body>
        </html>
    );
}
